### PR TITLE
GH-41: [Array] Make String and Binary consistent

### LINKED ISSUE #41: [Go] *array.Binary.ValueOffset doesn't work correctly
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/blob/main/go/arrow/array/binary.go#L76 -- this place is incorrect. For example, valueOffsets contain 6 offsets for the array with 5 elements, but calling array.ValueOffset(5) will cause the panic although the element exists.

It must be 
```
func (a *Binary) ValueOffset(i int) int {
	if i < 0 || i > a.array.data.length {
		panic("arrow/array: index out of range")
	}
	return int(a.valueOffsets[a.array.data.offset+i])
}
```

similar to strings https://github.com/apache/arrow/blob/main/go/arrow/array/string.go#L66.

### Component(s)

Go

### PR DESCRIPTION
**Pull request by zeroshade**
Fixes #41 

Makes the behavior of `ValueOffset` consistent between String and Binary arrays.

### CODE REVIEW

File: arrow/array/string_test.go [hunk 1]
```diff
@@ -90,9 +90,6 @@ func TestStringArray(t *testing.T) {
 		if got, want := arr.ValueOffset(i), int(offsets[i]); got != want {
 			t.Fatalf("arr-offset-beg[%d]: got=%d, want=%d", i, got, want)
 		}
-		if got, want := arr.ValueOffset(i+1), int(offsets[i+1]); got != want {
```
Comment (lidavidm) [inline arrow/array/string_test.go:93]: I guess we could validate ValueLen instead? Though maybe not really worth it

**Review by lidavidm — APPROVED** [review]
