### PR TITLE
fix(arrow/cdata): fix leaks identified by leak-sanitizer

### LINKED ISSUE #597: [Go] Release verification fails with Go 1.25
### Describe the bug, including details regarding any error messages, version, and platform.

I'm not able to test with Go 1.25 unless I disable the new leak sanitizer. The tests do pass with `ASAN_OPTIONS=detect_leaks=0`.

You see a lot of errors like

```
=================================================================
==125810==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 528 byte(s) in 15 object(s) allocated from:
    #0 0x7d5a317220c3 in calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:74
    #1 0x000000e15ace  (/tmp/go-build2352437442/b490/cdata.test+0xe15ace) (BuildId: 93af8cb8796c74ce229ab52de07b6bc975348205)
```

I poked around and it seems C Data tests use C.CString but never free the result; that may be the problem.

### Component(s)

Other

### PR DESCRIPTION
**Pull request by zeroshade**
### Rationale for this change
fixes #597

### What changes are included in this PR?
A series of calls to release, runtime.GC, free and so on to address all the leaks that were identified by the Go 1.25 sanitizer

### Are these changes tested?
go1.25 is added to the workflows to run the tests with ASAN which will catch these sanitizer issues in the future

### Are there any user-facing changes?
only the fixes

### CODE REVIEW

File: arrow/cdata/cdata_fulltest.c [hunk 1]
```diff
@@ -114,10 +114,12 @@ static void release_nested_internal(struct ArrowSchema* schema,
     for (int i = 0; i < schema->n_children; ++i) {
         ArrowSchemaRelease(schema->children[i]);
         free(schema->children[i]);
-    }
+    }
```
Comment (lidavidm) [inline arrow/cdata/cdata_fulltest.c]: nit: trailing whitespace
