### PR TITLE
fix(parquet/pqarrow): unsupported dictionary types in pqarrow

### LINKED ISSUE #490: [Go][Parquet] unsupported dictionary encoding types result in panic
### Describe the bug, including details regarding any error messages, version, and platform.

When a column is dictionary encoded but the type doesn't exist as a typed dictionary encoder, the columns writer panics.

To reproduce: run [this test](https://github.com/apache/arrow-go/blob/3c01efba60abe1421a49ac21c95858dbfccd78d6/parquet/pqarrow/encode_dictionary_test.go#L70-L111) with `arrow.PrimitiveTypes.Uint8` and observe a panic resulting from [this](https://github.com/apache/arrow-go/blob/3c01efba60abe1421a49ac21c95858dbfccd78d6/parquet/internal/encoding/typed_encoder.go#L165) type assertion. The underlying cause, in this specific case, is because the underlying type is `uint8` but the encoder is `int32`

### Component(s)

Parquet

### PR DESCRIPTION
**Pull request by zeroshade**
### Rationale for this change
fixes #490 

### What changes are included in this PR?
When using `PutDictionary` to write an arrow dictionary array to Parquet directly, we will now normalize the data type to a parquet physical storage type to avoid type problems. e.g. A dictionary with `int8` values will get cast to `int32` values before we process it so that all of the remaining encoding code can continue to be based on the physical storage type. This alleviates panics when using `pqarrow` to write Dictionary arrays.

### Are these changes tested?
Yes, the unit tests are updated to include tests for int8/uint8/etc. as dictionary value types.

### Are there any user-facing changes?
No, just fixing panics.

### CODE REVIEW

File: parquet/internal/encoding/types.go [hunk 1]
```diff
@@ -113,6 +113,14 @@ type DictEncoder interface {
 	// of [0,dictSize) and is not validated. Returns an error if a non-integral
 	// array is passed.
 	PutIndices(arrow.Array) error
+	// NormalizeDict takes an arrow array and normalizes it to a parquet
+	// native type. e.g. a dictionary of type int8 will be cast to an int32
+	// dictionary for parquet storage.
+	//
+	// The returned array must be released by the caller if different from
+	// the input array. If no normalization is needed, the input array
+	// may be returned as-is.
```
Comment (lidavidm) [inline parquet/internal/encoding/types.go]: That's kind of annoying, right? You have to branch. Maybe it should always require releasing (normalize can call retain)?

File: parquet/pqarrow/encode_arrow_test.go [hunk 2]
```diff
@@ -1352,6 +1352,7 @@ var fullTypeList = []arrow.DataType{
 }
 
 var dictEncodingSupportedTypeList = []arrow.DataType{
+	arrow.PrimitiveTypes.Int8,
```
Comment (amoeba) [inline parquet/pqarrow/encode_arrow_test.go:1355]: I'm not that familiar with the Go package yet, should this list include more of the possible types?

**Review by amoeba — APPROVED** [review]
Two tangential notes:

- Would it be good to title PRs like this fix(pqarrow): ... so users can skim changelogs for parquet changes?
- Does pqarrow smuggle Arrow schemas inside Parquet metadata so users can round-trip? This PR doesn't introduce any breakage of course but it strikes me that arrow -> parquet -> arrow won't round-trip well if the arrow input has to be cast like this.

File: parquet/pqarrow/encode_arrow_test.go (hunk 2 above)
Comment (zeroshade) [reply parquet/pqarrow/encode_arrow_test.go:1355]: testing at least one is generally sufficient, but I can add the other types easily to confirm.

File: parquet/internal/encoding/types.go (hunk 1 above)
Comment (zeroshade) [reply parquet/internal/encoding/types.go]: fair enough, i'll update to that.

File: parquet/pqarrow/encode_arrow_test.go (hunk 2 above)
Comment (amoeba) [reply parquet/pqarrow/encode_arrow_test.go:1355]: Thanks. I like having more tests when they're cheap.

**Comment by amoeba** [comment]
Thanks for the answers to my questions.

**Review by lidavidm — APPROVED** [review]
